---
name: "Publish to PyPI."
on:
  create:
    tags: ["*.*.*"]

jobs:
  publush:
    name: Publish new version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

