---
name: "Release new version"
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release new version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Automatic Tagging of Releases
        id: add-git-tag
        run: |
          bash  .github/scripts/tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        if: github.ref == 'refs/heads/master'